### ISSUE TITLE
Support for Magento 2?

### ISSUE THREAD

**Issue by goncalotomas** [magespecialist/lts2#1]
Just heard about your project from [this](http://magento.stackexchange.com/a/102262/36064) answer on Magento's Stack Exchange website. I'm using Magento 2 for my website. Do you plan to support Magento 2 in the future?

**Comment by phoenix128** [comment]
Hello Gonçalo,
MSP LTS2 cache has been designed for Magento1, Magento2 is a completely different platform.
Magento1 extensions are not compatible with Magento2.

Magento 2 already has an integrated FPC mechanism so we are not planning to port it.

**Comment by goncalotomas** [comment]
Thank you very much for the quick answer!
